//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.App.Services.Bill.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.App.Services.Bill.Business.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill found..
        /// </summary>
        public static string _102080001 {
            get {
                return ResourceManager.GetString("102080001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s discount found..
        /// </summary>
        public static string _102080002 {
            get {
                return ResourceManager.GetString("102080002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s status found..
        /// </summary>
        public static string _102080003 {
            get {
                return ResourceManager.GetString("102080003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s recipient found..
        /// </summary>
        public static string _102080004 {
            get {
                return ResourceManager.GetString("102080004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s recipient contact found..
        /// </summary>
        public static string _102080005 {
            get {
                return ResourceManager.GetString("102080005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s configuration found..
        /// </summary>
        public static string _102080006 {
            get {
                return ResourceManager.GetString("102080006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment found..
        /// </summary>
        public static string _102080007 {
            get {
                return ResourceManager.GetString("102080007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment&apos;s status found..
        /// </summary>
        public static string _102080008 {
            get {
                return ResourceManager.GetString("102080008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new payment. Please complete the existing payment or cancel it first..
        /// </summary>
        public static string _102080009 {
            get {
                return ResourceManager.GetString("102080009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No purchase order found..
        /// </summary>
        public static string _102080010 {
            get {
                return ResourceManager.GetString("102080010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer found..
        /// </summary>
        public static string _102080011 {
            get {
                return ResourceManager.GetString("102080011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courier&apos;s order found..
        /// </summary>
        public static string _102080012 {
            get {
                return ResourceManager.GetString("102080012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No area found..
        /// </summary>
        public static string _102080013 {
            get {
                return ResourceManager.GetString("102080013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user&apos;s channel found..
        /// </summary>
        public static string _102080014 {
            get {
                return ResourceManager.GetString("102080014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shop&apos;s account found..
        /// </summary>
        public static string _102080015 {
            get {
                return ResourceManager.GetString("102080015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courier&apos;s account found..
        /// </summary>
        public static string _102080016 {
            get {
                return ResourceManager.GetString("102080016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shipping found..
        /// </summary>
        public static string _102080017 {
            get {
                return ResourceManager.GetString("102080017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No billing found..
        /// </summary>
        public static string _102080018 {
            get {
                return ResourceManager.GetString("102080018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credit found..
        /// </summary>
        public static string _102080019 {
            get {
                return ResourceManager.GetString("102080019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No summary order found..
        /// </summary>
        public static string _102080020 {
            get {
                return ResourceManager.GetString("102080020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit not enough for issue parcel no..
        /// </summary>
        public static string _102080021 {
            get {
                return ResourceManager.GetString("102080021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request for parcel no. was problem..
        /// </summary>
        public static string _102080022 {
            get {
                return ResourceManager.GetString("102080022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document cannot be save..
        /// </summary>
        public static string _102080023 {
            get {
                return ResourceManager.GetString("102080023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document cannot be delete..
        /// </summary>
        public static string _102080024 {
            get {
                return ResourceManager.GetString("102080024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order cannot be mark as paid..
        /// </summary>
        public static string _102080025 {
            get {
                return ResourceManager.GetString("102080025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cancel order..
        /// </summary>
        public static string _102080026 {
            get {
                return ResourceManager.GetString("102080026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to confirm order..
        /// </summary>
        public static string _102080027 {
            get {
                return ResourceManager.GetString("102080027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new bill. Please complete the existing bill or cancel it first..
        /// </summary>
        public static string _102080028 {
            get {
                return ResourceManager.GetString("102080028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parcel found..
        /// </summary>
        public static string _102080029 {
            get {
                return ResourceManager.GetString("102080029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on update parcel..
        /// </summary>
        public static string _102080030 {
            get {
                return ResourceManager.GetString("102080030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s shipping found..
        /// </summary>
        public static string _102080031 {
            get {
                return ResourceManager.GetString("102080031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for pick up at home activate (Pick up).
        /// </summary>
        public static string _102080032 {
            get {
                return ResourceManager.GetString("102080032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for drop off at home activate (Drop off).
        /// </summary>
        public static string _102080033 {
            get {
                return ResourceManager.GetString("102080033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for standard delivery activate (Standard).
        /// </summary>
        public static string _102080034 {
            get {
                return ResourceManager.GetString("102080034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for express delivery activate (Express).
        /// </summary>
        public static string _102080035 {
            get {
                return ResourceManager.GetString("102080035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for transfer payment activate (Standard).
        /// </summary>
        public static string _102080036 {
            get {
                return ResourceManager.GetString("102080036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for cash on delivery payment activate (COD).
        /// </summary>
        public static string _102080037 {
            get {
                return ResourceManager.GetString("102080037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for insure goods activate (No).
        /// </summary>
        public static string _102080038 {
            get {
                return ResourceManager.GetString("102080038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function for not insure goods activate (Yes).
        /// </summary>
        public static string _102080039 {
            get {
                return ResourceManager.GetString("102080039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select courier..
        /// </summary>
        public static string _102080040 {
            get {
                return ResourceManager.GetString("102080040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tag found..
        /// </summary>
        public static string _102080041 {
            get {
                return ResourceManager.GetString("102080041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exist..
        /// </summary>
        public static string _102080042 {
            get {
                return ResourceManager.GetString("102080042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s tag found..
        /// </summary>
        public static string _102080043 {
            get {
                return ResourceManager.GetString("102080043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill&apos;s tag already exist..
        /// </summary>
        public static string _102080044 {
            get {
                return ResourceManager.GetString("102080044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment verification found..
        /// </summary>
        public static string _102080045 {
            get {
                return ResourceManager.GetString("102080045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment&apos;s setting found..
        /// </summary>
        public static string _102080046 {
            get {
                return ResourceManager.GetString("102080046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit not enough for verify slip..
        /// </summary>
        public static string _102080047 {
            get {
                return ResourceManager.GetString("102080047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit not enough for confirm bill..
        /// </summary>
        public static string _102080048 {
            get {
                return ResourceManager.GetString("102080048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill&apos;s notification found..
        /// </summary>
        public static string _102080049 {
            get {
                return ResourceManager.GetString("102080049", resourceCulture);
            }
        }
    }
}
